In [5]:
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to C:\Users\Ishika
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.


True

In [6]:
from nltk.corpus import brown

In [7]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [8]:
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [16]:
data = brown.sents(categories = ["romance"])

In [52]:
" ".join(data[40])

'but he might have been shooing away the fleas that hopped from his yellow dog onto him .'

## Tokenization

In [96]:
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Ishika
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [23]:
document = "Ishika loves to draw and code. She sleeps mostly otherwise. She loves to eat Biryani a lot. Be like her"
sentence = "Ishika loves to eat biryani"

In [24]:
sent = sent_tokenize(document)

In [25]:
sent

['Ishika loves to draw and code.',
 'She sleeps mostly otherwise.',
 'She loves to eat Biryani a lot.',
 'Be like her']

In [26]:
words = word_tokenize(sentence)

In [27]:
words

['Ishika', 'loves', 'to', 'eat', 'biryani']

## Removal of stopwords

In [32]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ishika
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [33]:
sw = set(stopwords.words("English"))

In [34]:
sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [35]:
print(words)

['Ishika', 'loves', 'to', 'eat', 'biryani']


In [37]:
def remove_stopwords(text, stopwords):
    useful = []
    useful = [w for w in text if w not in stopwords]
    return useful

In [38]:
useful_words = remove_stopwords(words, sw)

In [39]:
useful_words

['Ishika', 'loves', 'eat', 'biryani']

In [99]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful = tokenizer.tokenize(sentence)
print(useful)

['Ishika', 'loves', 'to', 'eat', 'biryani']


In [42]:
from nltk.stem import PorterStemmer

In [44]:
ps = PorterStemmer()

In [46]:
ps.stem("Laughing")

'laugh'

In [53]:
corpus = [
    "But this was not unusual , because youth in these quarters was always pushed at a distance from its elders .",
    "The way she strutted down the street , the Old Man would have been blind not to have noticed both .",
    "It's not for making pretty speeches about Dante those actresses get paid so good ",
    "but he might have been shooing away the fleas that hopped from his yellow dog onto him ."
]

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [55]:
cv = CountVectorizer()

In [61]:
vc = cv.fit_transform(corpus)
vc

<4x57 sparse matrix of type '<class 'numpy.int64'>'
	with 64 stored elements in Compressed Sparse Row format>

In [69]:
vc = vc.toarray()
print(vc)
print(cv.vocabulary_)

[[0 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 2 0 0 0 1]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0
  0 0 0 1 0 0 0 1 1 0 3 0 0 0 1 0 0 1 1 0 0]
 [1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 1
  1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0
  0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0]]
{'but': 9, 'this': 48, 'was': 52, 'not': 31, 'unusual': 51, 'because': 5, 'youth': 56, 'in': 25, 'these': 47, 'quarters': 38, 'always': 2, 'pushed': 37, 'at': 3, 'distance': 11, 'from': 17, 'its': 27, 'elders': 14, 'the': 46, 'way': 53, 'she': 39, 'strutted': 44, 'down': 13, 'street': 43, 'old': 33, 'man': 29, 'would': 54, 'have': 20, 'been': 6, 'blind': 7, 'to': 50, 'noticed': 32, 'both': 8, 'it': 26, 'for': 16, 'making': 28, 'pretty': 36, 'speeches': 42, 'about': 0, 'dante': 10, 'those': 49, 'actresses': 1, 'get': 1

In [70]:
print(len(cv.vocabulary_))

57


In [73]:
numbers = vc[0]

In [76]:
print(len(numbers))

57


In [100]:
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    # remove the stopwords
    words = remove_stopwords(words, sw)
    return words

In [101]:
 myTokenizer("Random testing is not so cool")

['random', 'testing', 'cool']

In [103]:
cv = CountVectorizer(tokenizer = myTokenizer)

In [105]:
vc = cv.fit_transform(corpus).toarray()

In [106]:
print(vc)

[[1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0]
 [0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0]]


In [108]:
len(vc[0])

32

In [111]:
print(cv.vocabulary_)

{'unusual': 27, 'youth': 31, 'quarters': 22, 'always': 2, 'pushed': 21, 'distance': 6, 'elders': 8, '.': 0, 'way': 28, 'strutted': 26, 'street': 25, 'old': 17, 'man': 14, 'would': 29, 'blind': 4, 'noticed': 16, 'making': 13, 'pretty': 20, 'speeches': 24, 'dante': 5, 'actresses': 1, 'get': 10, 'paid': 19, 'good': 11, 'might': 15, 'shooing': 23, 'away': 3, 'fleas': 9, 'hopped': 12, 'yellow': 30, 'dog': 7, 'onto': 18}
